import pandas as pd
import re


def ccp_series_list_in(f):
    """
    An import function specific to a peak list generated by 
    the Data Series functionality of the ccp analysis software.
    
    Originally written to import V135G slow exchange peak intensity
    series.  May have wonky functionality with other stuff.
    """
    
    df = pd.read_csv(f, sep="\t", na_values='-')
    # Selecting columns corresponding to actual peak intensities
    df = df[df.columns[2:-2]]
    res, resn = list(), list()
    for i in df.index:
        res.append(int(re.findall(r'\d+', i)[0]))
        resn.append(re.findall(r'[A-Z]{1}[a-z]{2}', i)[0])
    df['resn'] = resn
    df.index = res
    return df.sort_index().transpose()